config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'events/index'
  devise_for :users
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :events do
    resource :attendances
    resource :charges
  end
  resource :users, only: [:show] do
    resource :avatars, only: [:create]
  end

=begin
  namespace :admin do
    root 'base#index'
    resource :users, except: [:show]
    resource :events
  end
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event

    after_create :confirmation_send

    def confirmation_send
        AttendanceMailer.guest_email(self).deliver_now
    end
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :admin, class_name: 'User'
    has_one_attached :avatar

    validates :start_date,
        presence: true
        validate :not_in_past

    validates :duration,
        presence: true,
        numericality: {only_integer: true, greater_than: 0}
        validate :mustiple_of_5

    validates :title,
        presence: true,
        length: {minimum: 5, maximum:140}

    validates :description,
        presence: true,
        length: {minimum: 20, maximum:1000}

    validates :price,
        presence: true,
        numericality: {minimum: 1, maximum: 1000}

    validates :location,
        presence: true

    def not_in_past
        if start_date != nil
            if Time.now > start_date
                errors.add(:start_date, "La date de votre événement est dépassée !")
            end
        end
    end

    def mustiple_of_5
        if duration != nil
            if duration % 5 != 0
                errors.add(:duration, "La durée doit être un multiple de 5")
            end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances

  has_many :admins, foreign_key:'admin_id', class_name: 'Event'

  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper


    before_action :configure_devise_parameters, if: :devise_controller?
    #AUTORISER LA MODIFICATION DU FORMULAIRE DE LA GEM DEVISE
    def configure_devise_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  class EventController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
      @event = Event.all
    end

    def new
      @event = Event.new
    end

    def crate
      @event = Event.new(params_event)
      @event.admin_id = current_user.id
      if @event.save
        redirect_to event_path(@event.id)
        flash[:success] = "Votre évenement a bien été crée !"
      else
        render new_event_path
      end
    end

    def show
      @event = Event.find(params[:id])
      @count = count
      @end_date = end_date
      @participated = participated?
    end

    def edit
    end

    def destroy
    end

    private

    # Récupérer les infos de la création d'event
    def params_event
      params.require(:event).permit(:start_date, :duration, :title, :price, :description, :location, :avatar)
    end

    # Récupérer le nombre d'user inscrit à l'event
    def count
      Event.find(params[:id]).users.all.count
    end

    # Calcul de la date de fin, if faut passer la duration en minutes
    def end_date
      minutes = Event.find(params[:id]).durateion * 60
      (Event.find(params[:id]).start_date + minutes).strftime('%d of %B, %Y - %HH%M')
    end

    # Définir si il y'a eu participation à l'event
    def participated?
      Event.find(params['id']).users.ids
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   #EMPECHER LE USER D'ALLER SUR UNE AUTRE PAGE PROFIL QUE LA SIENNE
   before_action :authenticate_user!, :good_user

   def index
   end
 
   def show
     @user = User.find(current_user.id)
     @event_admin = Event.all
   end
 
 private
 
  def good_user
   @user = User.find(params['id'])
   if current_user.id == @user.id
   else
     redirect_to root_path
     flash[:danger]= "Bien essayé petit malin ! ;P"
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

    <h1 class="h3 mb-3 font-weight-normal text-center">Créer ton event !</h1>
  <!-- FORMULAIRE DE CRÉATION D'UN EVENT -->
  <%= form_with model: @event, local: true,  html: { class: "form-signin mt-3" } do |f| %>
    <p> Date de début :</br> <%= f.datetime_select :start_date, class: "form-control"%> </p>
    <p> Durée :</br> <%= f.text_field :duration, class: "form-control"%> </p>
    <p> Description :</br> <%= f.text_field :description, class: "form-control"%> </p>
    <p> Titre :</br> <%= f.text_field :title, class: "form-control"%> </p>
    <p> Prix d'entrée :</br> <%= f.text_field :price, class: "form-control"%> </p>
    <p> Lieu de l'Event :</br> <%= f.text_field :location, class: "form-control"%></p>
    <p> Image de l'event:</br>  <%= f.file_field :avatar, class: "form-control" %></p>
    <div class="actions mt-5">
      <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
    </div>
  <%end%>
</div>

<% if @event.errors.any? %>
  <div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong> Bah alors ?! </strong>
  <p>Nous n'avons pas réussi à créer l'Event pour le/les raisons suivantes :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

</div>
</div>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

    <h1 class="h3 mb-3 font-weight-normal text-center">Créer ton event !</h1>
  <!-- FORMULAIRE DE CRÉATION D'UN EVENT -->
  <%= form_with model: @event, local: true,  html: { class: "form-signin mt-3" } do |f| %>
    <p> Date de début :</br> <%= f.datetime_select :start_date, class: "form-control"%> </p>
    <p> Durée :</br> <%= f.text_field :duration, class: "form-control"%> </p>
    <p> Description :</br> <%= f.text_field :description, class: "form-control"%> </p>
    <p> Titre :</br> <%= f.text_field :title, class: "form-control"%> </p>
    <p> Prix d'entrée :</br> <%= f.text_field :price, class: "form-control"%> </p>
    <p> Lieu de l'Event :</br> <%= f.text_field :location, class: "form-control"%></p>
    <p> Image de l'event:</br>  <%= f.file_field :avatar, class: "form-control" %></p>
    <div class="actions mt-5">
      <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
    </div>
  <%end%>
</div>

=begin
<% if @event.errors.any? %>
  <div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong> Bah alors ?! </strong>
  <p>Nous n'avons pas réussi à créer l'Event pour le/les raisons suivantes :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
=end

  </div>
</div>

app/views/events/show.html.erb
<!-- MESSAGE SI CONNEXION RÉUSSIE -->
<% if flash[:success] %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <h2>Ton event à bien été enregistré ! </h2>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
<% end %>

<% if flash[:success2] %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <h2>Ton event à bien été enregistré ! </h2>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
<% end %>

<div class='container mt-4'>
  <br>
  <h1><%= @event.title %></h1>
  <!-- INFORMATION SUR L'UTILISATEUR -->
  <br>
  <div class= 'border border-white mt-4 pt-4 pl-2' style="max-width: 50rem; font-size: 18px;">
    <p>
      <u>Date de début</u>: <%= @event.start_date.strftime('%d of %B, %Y - %HH%M') %><br>
      <u>Date de fin</u>: <%= @end_date %><br>
      <u>Créateur de l'Event</u>: <%= User.find(@event.admin_id).email %><br>
      <u>Lieu de l'Event</u>: <%= @event.location %><br>
      <u>Description</u>: <%= @event.description %><br>
      <u>Prix</u>: <%= @event.price%> €<br>
      <!-- Methode count en private pour le nombre d'inscrits -->
      <u>Nombre d'inscrits</u>: <%= @count %><br>
    </p>
  </div>

  <%if @event.avatar.attached?%>
    <%= image_tag @event.avatar, alt: 'avatar' %>
  <%else%>
    <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
  <%end%>
  
  <div>
    <br>
    <% if current_user %>
      <% if current_user.id != @event.admin_id %>
      <% if @participated.include? current_user.id %>
      <%else%>
        <%= link_to new_event_attendance_path(params['id']) do %>
          <button type="button" class="btn btn-success">Participer à l'évenement</button>
        <% end %>
      <% end %>
      <%end%>
    <% end %>
  </div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpEventBrightKegre</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Baloo's Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ">
      <li class="nav-item">
        <a class="nav-link" href="/events/new">Create Event</a>
      </li>

      <% if user_signed_in? %>

        <li class="nav-item">
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon profil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Mon profil", class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, "data-method": :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>

          <li class="nav-item">
            <div class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sign Up / Login
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              </div>
            </div>
          </li>

        <% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class='container mt-4'>
  <br>
  <h1>Mon profil</h1>
  <!-- INFORMATION SUR L'UTILISATEUR -->
  <br>

  <%if @user.avatar.attached?%>
    <%= image_tag @user.avatar, alt: 'avatar' %>
  <%else%>
    <%= avatar_for(current_user) %>  <%end%>
  <div class= 'border border-white mt-4 pt-4 pl-2' style="max-width: 50rem; font-size: 18px;">
    <p>
      <u>Prénom</u>: <%= @user.first_name %><br>
      <u>Nom</u>: <%= @user.last_name %><br>
      <u>Description</u>: <%= @user.description %><br>
      <u>Email</u>: <%= @user.email %><br>
    </p>
    <%= form_tag user_avatars_path(@user), multipart: true do %>
      <%= file_field_tag :avatar %>
      <%= submit_tag "mettre à jour" %>
    <% end %>

  </div>
  <%= link_to edit_user_registration_path do %>
<button type="button" class="btn btn-warning mt-4">Edit Password / Mail </button>
<% end %>
</div>
<br>

<center>
  <h4>L'utilisateur à créer ces événements: </h4>
  <div class = 'mt-4 pt-4 pl-2'>
    <div class="card-columns">
      <!-- APPELLE DE CHAQUE ELEMENT DU TABLEAU EVENT -->
      <% @event_admin.sort.each do |event| %>
        <% if event.admin_id == current_user.id %>
          <!-- link_to POUR QUE TOUTE LA CARTE DEVIENNE UN LIEN -->
          <%= link_to event_path(event), :controller => :events do%>

            <div class="card border-primary mb-3 bg-light" style="max-width: 20rem;">
              <div class="card-body">

                <!-- AFFICHAGE DU TITRE, LIÉ À SA PAGE show -->
                <h2 class="card-title text-dark">  <%= event.title%></h2>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</center>